--- 
javascripts: 
- base:
  - rails
  - application
- ipad:
  - base
  - application
  - jquery
  - jquery.mobile
  - jqm-docs

stylesheets: 
- base: 
  - default
- admin:
  - default
  - admin
- dialog:
  - dialog
- ipad:
  - dialog
  - jquery.mobile
  - jqm-docs

# rails, application
# default, admin